# Generated by Django 3.1.1 on 2020-09-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_pods', models.CharField(choices=[('COFFEE_POD_LARGE', 'COFFEE_POD_LARGE'), ('COFFEE_POD_SMALL', 'COFFEE_POD_SMALL'), ('ESPRESSO_POD', 'ESPRESSO_POD')], max_length=50)),
                ('coffee_flavors', models.CharField(choices=[('COFFEE_FLAVOR_VANILLA', 'COFFEE_FLAVOR_VANILLA'), ('COFFEE_FLAVOR_CARAMEL', 'COFFEE_FLAVOR_CARAMEL'), ('COFFEE_FLAVOR_PSL', 'COFFEE_FLAVOR_PSL'), ('COFFEE_FLAVOR_MOCHA', 'COFFEE_FLAVOR_MOCHA'), ('COFFEE_FLAVOR_HAZELNUT', 'COFFEE_FLAVOR_HAZELNUT')], max_length=50)),
                ('pack_sizes', models.CharField(choices=[('1_dozen', '1_dozen'), ('3_dozen', '3_dozen'), ('5_dozen', '5_dozen'), ('7_dozen', '7_dozen')], max_length=50)),
            ],
        ),
    ]
