# Generated by Django 3.1.1 on 2020-09-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_machine', models.CharField(choices=[('COFFEE_MACHINE_LARGE', 'COFFEE_MACHINE_LARGE'), ('COFFEE_MACHINE_SMALL', 'COFFEE_MACHINE_SMALL'), ('ESPRESSO_MACHINE', 'ESPRESSO_MACHINE')], max_length=50)),
                ('model_types', models.CharField(choices=[('base_model', 'base_model'), ('premium_model', 'premium_model'), ('deluxe_model', 'deluxe_model')], max_length=50)),
                ('water_line_compatible', models.BooleanField()),
            ],
        ),
    ]
