# Generated by Django 3.1.1 on 2020-09-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='product_type_machine',
            field=models.CharField(choices=[('CL00', 'COFFEE_MACHINE_LARGE'), ('CM00', 'COFFEE_MACHINE_SMALL'), ('EM00', 'ESPRESSO_MACHINE')], max_length=50),
        ),
    ]
