# Generated by Django 3.1.1 on 2020-09-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_machine', '0003_auto_20200914_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='slug',
            new_name='sku',
        ),
    ]
